version: '2'
services:

  group_sign:
    build:
      context: .
      args:
        DOCKER_CC_FLAGS: "-O2"
        #DOCKER_CC_FLAGS: "-g4"
    container_name: group-sign
    environment:
      REDIS: redis-server
      SOURCEMAP_PATH: /group-sign/server/sourcemap.json
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - group_sign_redis:redis-server

  group_sign_redis:
    image: redis
    container_name: group-sign-redis
    expose:
      - 6379
